# Generated by Django 4.1.7 on 2023-05-12 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField()),
                ('order_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=16)),
                ('fermentation', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='tea/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Teas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type_packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging', models.CharField(choices=[('Сake', 'Сake'), ('Sphere', 'Sphere'), ('Bowl', 'Bowl'), ('Loose', 'Loose'), ('Brick', 'Brick')], default='Loose', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('user_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cities')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.products')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.weight')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='packaging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.type_packaging'),
        ),
        migrations.AddField(
            model_name='products',
            name='tea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.teas'),
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qty', models.IntegerField()),
                ('product_price', models.FloatField()),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.products')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.users'),
        ),
    ]
